CompatHelper: bump compat for BSplineKit to 0.18, (keep existing compat) (#104)
* CompatHelper: bump compat for BSplineKit to 0.18, (keep existing compat)

* Update Project.toml

* explicit import of fit

---------

Co-authored-by: CompatHelper Julia <compathelper_noreply@julialang.org>
Co-authored-by: Phillip Alday <palday@users.noreply.github.com>
Co-authored-by: Phillip Alday <me@phillipalday.com>

diff --git a/.github/workflows/style.yml b/.github/workflows/style.yml
--- a/.github/workflows/style.yml
+++ b/.github/workflows/style.yml
@@ -1,35 +1,34 @@
 name: Style-Enforcer
 on:
-  push:
-    branches:
-      - 'main'
-    tags: '*'
   pull_request:
     types: [opened, synchronize, reopened, ready_for_review]
-    # note: keep in sync with `format/run.jl`
     paths-ignore:
       - 'README.md'
       - '.gitignore'
 jobs:
   format-check:
     name: Style Enforcement
-    # Run on push's or non-draft PRs
-    if: (github.event_name == 'push') || (github.event.pull_request.draft == false)
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        julia-version: [1.9]
+        julia-version: [min]
     steps:
+      - uses: actions/checkout@v4
       - uses: julia-actions/setup-julia@latest
         with:
           version: ${{ matrix.julia-version }}
-      - uses: actions/checkout@v4
-      - name: Instantiate `format` environment and format
+      - name: Install JuliaFormatter
+        shell: julia --project=@format --color=yes {0}
         run: |
-          julia --project=format -e 'using Pkg; Pkg.instantiate()'
-          julia --project=format 'format/run.jl'
+          using Pkg
+          Pkg.add(PackageSpec(; name="JuliaFormatter", version="1"))
+      - name: Check formatting
+        shell: julia --project=@format --color=yes {0}
+        run: |
+          using JuliaFormatter
+          format(".", YASStyle(); verbose=true) || exit(1)
+      # Add formatting suggestions to non-draft PRs even if "Check formatting" fails
       - uses: reviewdog/action-suggester@v1
-        if: github.event_name == 'pull_request'
+        if: ${{ !cancelled() && github.event.pull_request.draft == false }}
         with:
           tool_name: JuliaFormatter
-          fail_on_error: true
