upgrade formatter

diff --git a/.github/workflows/style.yml b/.github/workflows/style.yml
--- a/.github/workflows/style.yml
+++ b/.github/workflows/style.yml
@@ -18,18 +18,24 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        julia-version: [1.9]
+        julia-version: [min]
     steps:
       - uses: julia-actions/setup-julia@latest
         with:
           version: ${{ matrix.julia-version }}
       - uses: actions/checkout@v4
-      - name: Instantiate `format` environment and format
+      - name: Install JuliaFormatter
+        shell: julia --project=@format --color=yes {0}
         run: |
-          julia --project=format -e 'using Pkg; Pkg.instantiate()'
-          julia --project=format 'format/run.jl'
-      - uses: reviewdog/action-suggester@v1
-        if: github.event_name == 'pull_request'
+          using Pkg
+          Pkg.add(PackageSpec(; name="JuliaFormatter", version="1"))
+      - name: Check formatting
+        shell: julia --project=@format --color=yes {0}
+        run: |
+          using JuliaFormatter
+          format("."; verbose=true) || exit(1)
+      # Add formatting suggestions to non-draft PRs even if when "Check formatting" fails
+      - uses: reviewdog/action-suggester@a3026c6020837c23b61a79d12db223a00df19e6a # v1.19.0
+        if: ${{ !cancelled() && github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
         with:
           tool_name: JuliaFormatter
-          fail_on_error: true
